export const enum eThemeLeptonXComponents {
  ApplicationLayout = 'Theme.ApplicationLayoutComponent',
  AccountLayout = 'Theme.AccountLayoutComponent',
  Footer = 'Theme.FooterComponent',
  EmptyLayout = 'Theme.EmptyLayoutComponent',
  Logo = 'Theme.LogoComponent',
  Routes = 'Theme.RoutesComponent',
  NavItems = 'Theme.NavItemsComponent',
  CurrentUser = 'Theme.CurrentUserComponent',
  CurrentUserImage = 'Theme.CurrentUserImageComponent',
  Languages = 'Theme.LanguagesComponent',
  Navbar = 'Theme.NavbarComponent',
  Sidebar = 'Theme.Sidebar',
  Login = 'Theme.LoginComponent',
  Breadcrumb = 'Theme.BreadcrumbComponent',
  MobileNavbar = 'Theme.MobileNavbarComponent',
  MobileUserProfile = 'Theme.MobileUserProfileComponent',
  MobileLanguageSelection = 'Theme.MobileLanguageSelectionComponent',
  PageAlertContainer = 'Theme.PageAlertContainerComponent',
  Toolbar = 'Theme.ToolbarComponent',
  Settings = 'Theme.SettingsComponent',
}
